version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.19
jobs:
  aws-send-command:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
      - run: ./build.sh ${EC2_INSTANCE_ID}
workflows:
  version: 2
  build_to_aws:
    jobs:
      - aws-send-command